# Q-Table Learning

In [1]:
import gym
import numpy as np

Load the environment

In [2]:
# List all the environments
# print(gym.envs.registry.all())

In [3]:
env = gym.make('FrozenLake-v0')

Implementing Q-Table learning algorithm

In [4]:
# Initialize the empty table with zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [5]:
# Set the learning parameters
lr = 0.8
y = 0.95
num_episodes = 2000
reward_list = []

In [8]:
# Start looping through and fill the table
for i in range(num_episodes):
    
    # Reset the environment and get the first observation
    s = env.reset()
    total_reward = 0
    done = False
    j = 0
    
    # The Q-Table learning algorithm
    while j < 99:
        
        # Using greedy approach to pick and action
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n) * (1.0/(i+1)))
        
        # Get the next state and reward
        s_new, reward, done, _ = env.step(a)
        
        # Update the Q-Table
        Q[s,a] = Q[s,a] + lr * (reward + y*np.max(Q[s_new,:]) - Q[s,a])
    
        # Get the cumilative reward
        total_reward += reward
        
        # Update the current scene
        s = s_new
        
        if done == True:
            break
      
    # Add the total rewards to the final reward list to view over time
    reward_list.append(total_reward)

In [10]:
print("Score over time: " + str(sum(reward_list)/num_episodes))

Score over time: 0.6225


In [12]:
print("Final Q Table")
print(Q)

Final Q Table
[[4.00306003e-01 1.55964338e-02 1.22298821e-02 0.00000000e+00]
 [1.04159853e-04 4.41806236e-04 1.43675049e-03 2.46995663e-01]
 [6.81299900e-03 2.04788601e-03 4.55860911e-03 7.91253845e-02]
 [5.68510577e-04 6.24977373e-03 0.00000000e+00 3.10643409e-02]
 [3.20735189e-01 1.06287151e-03 5.89036108e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.23403152e-04 2.07631087e-06 1.35660770e-02 1.71271771e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.59323994e-04 0.00000000e+00 1.09038795e-05 1.96517643e-01]
 [0.00000000e+00 3.30911049e-01 0.00000000e+00 8.50685332e-03]
 [8.50296407e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.78160333e-04 7.38396858e-01 0.00000000e+00]
 [0.00000000e+00 9.69142335e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.0000000